name: Static nm-configurator config
stages:
  initramfs:
  - directories:
      - path: /tmp/nmc/static/desired-states
        permissions: 448
        owner: 0
        group: 0
      - path: /tmp/nmc/static/network-config
        permissions: 448
        owner: 0
        group: 0
    files:
      - path: /tmp/nmc/static/desired-states/node1.yaml
        permissions: 384
        owner: 0
        group: 0
        content: |
          dns-resolver:
            config:
              server:
              - 192.168.122.1
              search: []
          routes:
            config:
            - destination: 0.0.0.0/0
              next-hop-interface: eth0
              next-hop-address: 192.168.122.1
              metric: 150
              table-id: 254
          interfaces:
          - name: eth0
            type: ethernet
            state: up
            mac-address: 52:54:00:45:14:c5
            ipv4:
              address:
              - ip: 192.168.122.150
                prefix-length: 24
              enabled: true
            ipv6:
              enabled: false
        encoding: ""
        ownerstring: ""
      - path: /tmp/nmc/static/desired-states/node2.yaml
        permissions: 384
        owner: 0
        group: 0
        content: |
          dns-resolver:
            config:
              server:
              - 192.168.122.1
              search: []
          routes:
            config:
            - destination: 0.0.0.0/0
              next-hop-interface: eth0
              next-hop-address: 192.168.122.1
              metric: 150
              table-id: 254
          interfaces:
          - name: eth0
            type: ethernet
            state: up
            mac-address: 52:54:00:3a:ae:3b
            ipv4:
              address:
              - ip: 192.168.122.151
                prefix-length: 24
              enabled: true
            ipv6:
              enabled: false
        encoding: ""
        ownerstring: ""
    commands:
    - nmc generate --config-dir /tmp/nmc/static/desired-states --output-dir /tmp/nmc/static/network-config
    - nmc apply --config-dir /tmp/nmc/static/network-config
